.PHONY: clean All

All:
	@echo "----------Building project:[ greeting - Debug ]----------"
	@"$(MAKE)" -f  "greeting.mk"
clean:
	@echo "----------Cleaning project:[ greeting - Debug ]----------"
	@"$(MAKE)" -f  "greeting.mk" clean
